FROM agners/archlinuxarm-arm64v8

RUN pacman --noconfirm -Syu
RUN pacman --noconfirm -S base-devel git gdb cmake libx11 glu libxrandr libxinerama libxcursor libxi alsa-lib gtk2 jack2 jq zip wget unzip vim nasm yasm lame vim
