FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y install git build-essential curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev wget unzip vim jq
